[build]
builder = "DOCKERFILE"
dockerfilePath = "api/Dockerfile"

[deploy]
startCommand = "bundle exec puma -C puma.rb"
healthcheckPath = "/healthz"
healthcheckTimeout = 20
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[variables]
RACK_ENV = "production"
RACK_MAX_THREADS = "8"
WEB_CONCURRENCY = "2"
